server:
  port: 7000
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
         uri: https://github.com/hll809906180/springboot-config-center/   # 配置git仓库的地址
         search-paths: pdf-repo                                               # git仓库地址下的相对地址，可以配置多个，用,分割。
         username: hll809906180                                               # git仓库的账号
         password: hll920227                                                  # git仓库的密码

eureka:
  client:
    service-url:
      defaultZone: http://user1:password123@peer1:8000/eureka/,http://user2:password123@peer2:8001/eureka/