server:
  port: 8087
spring:
  application:
    name: microservice-consumer-movie-feign-hystrix
eureka:
  client:
    service-url:
      defaultZone: http://user1:password123@peer1:8000/eureka/,http://user2:password123@peer2:8001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
# Disable HystrixCommands For FeignClients By Default
# https://github.com/spring-cloud/spring-cloud-netflix/issues/1277
# 开启 hystrix 功能
feign:
  hystrix:
    enabled: true
#actuator  启用所有的监控端点 “*”号代表启用所有的监控端点，可以单独启用，例如，health，info，metrics
#  spring boot 升为 2.0 后，为了安全，默认 Actuator 只暴露了2个端点，heath 和 info，继续
# 访问  http://192.168.1.103:7901/actuator/metrics
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
      health:
        show-details: ALWAYS
# feign和hystrix配合使用过程中，hystrix的默认超时时间为1s，feign的结果1s内没返回，即认为超时
# 因为feign 使用的ribbon 所以ribbon 也要设置
ribbon:
  ReadTimeout:  30000
  ConnectTimeout:  15000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
