server:
  port: 7100
spring:
#  cloud:
#    bus:
#      trace:
#        enabled: true
#  rabbitmq:
#    host: 192.168.9.89
#    port: 5672
#    username: admin
#    password: 123456
  application:
    name:  microservice-config-client

management:
  security:
    enabled: false